### PR TITLE
Proposed fix for #348

### PR DESCRIPTION
**Pull request by jenssegers**
See issue #348

### CODE REVIEW

**Comment by someara** [comment]
tried reopening but the repo disappeard

**Comment by jenssegers** [comment]
Yeah, I deleted the fork after my PR. Will you add these manually or should I do a new PR?

**Comment by someara** [comment]
I can add them manually. They're still cached in the Github UI =)

**Comment by jenssegers** [comment]
Any news on this?

**Comment by jenssegers** [comment]
Any news on this?

**Comment by someara** [comment]
I had this in for 6.0.30, but reverted it for 6.0.31.

It was breaking Debian / Ubuntu somehow

https://github.com/chef-cookbooks/mysql/commit/a6f1eb25db4f158406ef01d6a948771dd6313eec

-s

**Pull request closed without merging**
