### PR TITLE
Mysql 5.7.15 Ubuntu 1604

### PR DESCRIPTION
**Pull request by PrimarDarren**
### Description

Minor update to selection of mysql instance template to workaround chown bug in mysql 5.7.15 package on Ubuntu 16.04
mysql was using chown on the data dir even though no change was needed

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by PrimarDarren** [comment]
Hi all

We have since signed the CLA.

Please advise if any issues.

Regards,

Darren

**Comment by tas50** [comment]
I'm a bit uncomfortable implementing this change to work around a bug in the package. Is this a bug identified upstream that we can just wait on the fix for?  I'd be much more comfortable letting the package maintainers fix their bug vs. working around it here.

**Comment by PrimarDarren** [comment]
Yes I understand the concern, this work-around is version-specific. Though the version that has the bug fixed will not have the workaround applied due to conditional code. This alteration is just a slightly more specific version-driven configuration at the package version level instead of the version level. It will help anyone else aiming to deploy to mysql-5.7 5.7.15-0ubuntu0.16.04.1. If others have security compliance goals to ensure mysqld doesn't get chown capability or to prevent mysqld being able to write to the data_dir itself, their compliance verification checks will detect the situation. This change won't prevent that. Otherwise this cookbook doesn't support multi-server installs for package version mysql-5.7 5.7.15-0ubuntu0.16.04.1?

**Comment by PrimarDarren** [comment]
Apparently the bug was meant to be fixed in 5.7.10?  We aim to protect our deployments from delays/regressions in upstream bug fixes. https://bugs.mysql.com/bug.php?id=78591

**Comment by iennae** [comment]
We've removed the embedded versions from the library. Can you take a look and refactor your changes? Thanks!

**Comment by tas50** [comment]
I'm going to close this out since the real solution is to use the fixed maintainer package.

**Pull request closed without merging**
