### PR TITLE
Fix apparmor blocking writes to non-default tmp_dirs

### PR DESCRIPTION
**Pull request by ExplodingCabbage**
Without this change, we'd get errors like this when running Chef:

```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0, 1, 2], but received '141'
---- Begin output of "bash"  "/tmp/chef-script20160308-2620-vdadfn" ----
STDOUT: Installing MySQL system tables...
STDERR: 2016-03-08 13:54:59 0 [Note] /usr/sbin/mysqld (mysqld 5.6.28-0ubuntu0.14.04.1) starting as process 7762 ...
---- End output of "bash"  "/tmp/chef-script20160308-2620-vdadfn" ----
Ran "bash"  "/tmp/chef-script20160308-2620-vdadfn" returned 141

Resource Declaration:
---------------------
# In /var/chef/runs/14049d19-d3d6-4ba2-8e78-1e53a4ad4e3b/local-mode-cache/cache/cookbooks/mysql/libraries/provider_mysql_service_base.rb

145:         bash "#{new_resource.name} :create initial records" do
146:           code init_records_script
147:           returns [0, 1, 2] # facepalm
148:           not_if "/usr/bin/test -f #{parsed_data_dir}/mysql/user.frm"
149:           action :run
150:         end
151:       end

Compiled Resource:
------------------
# Declared in /var/chef/runs/14049d19-d3d6-4ba2-8e78-1e53a4ad4e3b/local-mode-cache/cache/cookbooks/mysql/libraries/provider_mysql_service_base.rb:145:in `block in <class:MysqlServiceBase>'

bash("default :create initial records") do
  action [:run]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  command "default :create initial records"
  backup 5
  returns [0, 1, 2]
  code "        set -e\n        rm -rf /tmp/mysql-default\n        mkdir /tmp/mysql-default\n\n        cat > /tmp/mysql-default/my.sql <<-EOSQL\nUPDATE mysql.user SET password=PASSWORD('root') WHERE user = 'root';\nDELETE FROM mysql.user WHERE USER LIKE '';\nDELETE FROM mysql.user WHERE user = 'root' and host NOT IN ('127.0.0.1', 'localhost');\nFLUSH PRIVILEGES;\nDELETE FROM mysql.db WHERE db LIKE 'test%';\nDROP DATABASE IF EXISTS test ;\nEOSQL\n\n       mysql_install_db --defaults-file=/etc/mysql-default/my.cnf --datadir=/mnt/took/mysql/ --explicit_defaults_for_timestamp\n       /usr/sbin/mysqld --defaults-file=/etc/mysql-default/my.cnf --init-file=/tmp/mysql-default/my.sql --explicit_defaults_for_timestamp &\n\n       while [ ! -f /run/mysql-default/mysqld.pid ] ; do sleep 1 ; done\n       kill `cat /run/mysql-default/mysqld.pid`\n       while [ -f /run/mysql-default/mysqld.pid ] ; do sleep 1 ; done\n       rm -rf /tmp/mysql-default\n"
  interpreter "bash"
  declared_type :bash
  cookbook_name "took_role"
  not_if "/usr/bin/test -f /mnt/took/mysql//mysql/user.frm"
end
```

Thanks to my friend and colleague @fabianhoward for doing most of the work figuring this out.

I'm not certain this is the cleanest way of fixing this or whether there are other cases where AppArmor will still cause problems - all I know is that we had AppArmor denials happening on the 

```
mysql_install_db --defaults-file=/etc/mysql-default/my.cnf --datadir=/mnt/took/mysql/ --explicit_defaults_for_timestamp
```

command until we made this change. I leave the question of whether this change is the right thing to do and whether to merge it in your hands.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @ExplodingCabbage

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by iennae** [comment]
@ExplodingCabbage,

Can you confirm whether the change:

PR #414 of adding the umask resolves the issue as well? This looks like the same area of code, so wondering if that will resolve your problem.

Thanks!

**Comment by iennae** [comment]
@ExplodingCabbage,

Can you confirm whether PR #414 resolves this? Thanks!

**Comment by ExplodingCabbage** [comment]
@iennae 

Short answer: no, but I don't really understand wtf is going on very well.

Long answer: Hmm. My grasp of AppArmor is admittedly weak, but I don't understand how the two can be related; #414 changes file permissions, which dictate what particular *users* are allowed to do, but AppArmor, as I understand dictates what particular *executables* are allowed to do. It's an extra layer of restrictions entirely (I think?) unaffected by file permissions.

It's been a while since I touched this stuff, but I *think* testing against the current master branch of https://github.com/chef-cookbooks/mysql confirms this? My build reproducibly fails with exactly the same error as I quoted in the OP if I try to build with your current master instead of mine, whereas with my version of the mysql repo my build reproducibly works. I'm *slightly* confused because I think I recall previously seeing explicit AppArmor denials in my `/var/log/kern.log` prior to authoring my fix, and I don't see them any more; I'm not sure if I'm misremembering or if #414 has somehow suppressed the error logging I used to see (which would make *no sense* given my understanding of how AppArmor works) without actually fixing the bug.

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Pull request merged**
