### PR TITLE
Integration tests refactoring

### PR DESCRIPTION
**Pull request by aleksey-hariton**
### Description

 - Added full test list to Travis, according to [Platform Support](https://github.com/chef-cookbooks/mysql/#platform-support) table
 - Refactored helper methods for integration tests, to simplify new tests development
 - Reduced code duplication in integration tests
 - Used different password for slaves and master in `smoke` recipe, to improve tests quality
 - Removed needless tests from integration tests (master-slave tests almost all cases except independent client installation)

### Issues Resolved

- Issue with integration tests on Debian 7 & 8

### TODO

Find out why SUSE doesn't install header files for MySQL

### CODE REVIEW

**Comment by aleksey-hariton** [comment]
@someara have no idea how I closed original PR... Signed.

**Comment by aleksey-hariton** [comment]
Looks like we have some kind of race condition, will try to reproduce

**Comment by someara** [comment]
Thanks Aleksey!

**Comment by aleksey-hariton** [comment]
@someara mb you can help me also with this https://github.com/sethvargo/stove/pull/103#issuecomment-271246280

@tas50 merged PR but didn't release new version of gem, I don't like git sources in my Berksfile :smiley:

**Pull request merged**
