### PR TITLE
Suppresses removed timestamp option on v57plus

### PR DESCRIPTION
**Pull request by w3iBStime**
The 'explicit_defaults_for_timestamp' option on mysqld is deprecated in 5.6 and was apparently removed in 5.7:

"* bash[phpci initial records] action run
        [execute] mysql_install_db: [ERROR] unknown option '--explicit_defaults_for_timestamp'
                  2016-11-30 09:53:13 [ERROR]   Unrecognized options"

Also see note under https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp

### CODE REVIEW

**Comment by w3iBStime** [comment]
FWIW, I tried to run the tests with rake -T but I got the following. TomlRb should be available because I also ran chef exec bundle update and it said it installed that dependency and appeared successful. Chef and Ruby aren't really my forte but this is a pretty simple change.

`$ rake -T

*** TomlRb not available. Skipping the Maintainers Rake task

>>> Gem load error: cannot load such file -- cookstyle, omitting style:ruby
>>> Gem load error: cannot load such file -- cookstyle, omitting style:chef
>>> Gem load error: cannot load such file -- rspec/core/rake_task, omitting spec
rake aborted!
cannot load such file -- kitchen/rake_tasks
/Users/brett.stime/code/3rdParty/cookbook-mysql-nativex/Rakefile:48:in `block in <top (required)>'
/Users/brett.stime/code/3rdParty/cookbook-mysql-nativex/Rakefile:46:in `<top (required)>'
(See full trace by running task with --trace)`

**Comment by tas50** [comment]
You'll need to sign off this commit for the DCO as well

**Comment by w3iBStime** [comment]
I don't think the Travis alerts are related to my change.

**Comment by iennae** [comment]
As this is an obvious fix, I'm going to go ahead and pull it in. Thanks for the contribution!

**Pull request merged**
