### PR TITLE
Handle stop timeout

### PR DESCRIPTION
**Pull request by kcd83**
Seems the stop messages and timeout have been only half baked. This resolves what I believe was originally intended.

### CODE REVIEW

**Comment by someara** [comment]
Dupe #355. Fixed up in v6.0.23

**Comment by kcd83** [comment]
Thanks for looking into this however #355 is not a duplicate of this. This request addresses _stop_ where as 355 addresses _start_.

`STOPTIMEOUT` is never used. The response code returns success if `kill` is successfully called and not if mysql is successfully stopped and for some reason the `print_stop_success` function isn't used.

I do agree extending the timeout for stop is useful too

**Comment by kcd83** [comment]
@someara is this better as a an issue rather than a merge request?

**Comment by someara** [comment]
Let's keep it as a PR for now.. I treat them essentially same for the time
being.
I'll have some time to give this some proper attention later in the week.

-s

**Pull request closed without merging**
