### PR TITLE
outthentic integration tests for mysql server

### PR DESCRIPTION
**Pull request by melezhik**
Hi this integration [tests suite](https://sparrowhub.org/info/outth-mysql-cookbook?v=0.000007) for mysql cookbook 

An example Travis builds could be viewed here - https://travis-ci.org/melezhik/mysql/builds/103823936

### CODE REVIEW

**Comment by melezhik** [comment]
Hi guys! Any news here?

**Comment by melezhik** [comment]
HI @someara ! Any news here?

**Comment by iennae** [comment]
@melezhik,

Apologies for the delay in responding. Is sparrow like swat? Unfortunately this is not going to be added to the mysql cookbook at this time. It has the same issues as with the httpd cookbook.

* It's functionality has limited use at current time.
* It is functionality that only you have knowledge of at this time, meaning it has fragility in terms of incorporating into core projects. You are a single point of knowledge. (SPOK)
* It's written in perl, which leads to additional complexity in terms of additional folks supporting it. Ruby and shell are both commonly known in the Chef community in writing cookbooks. This may impact it's adoption and use. Personally, I love perl, so it's not a ding against using perl, just the ability to remedy the SPOK situation.

While to you this may seem like the next logical step, as maintainers for this cookbook, we have to consider the costs and benefits to the whole community who depend on this cookbook to just work. This is too costly of an addition to this cookbook at this time.

I encourage you to continue blogging about it, and getting additional support from the community. I also encourage you to create and release quality cookbooks to the community on the supermarket: supermarket.chef.io that include your testing framework. As support grows for your cookbooks, this will lead to additional use.

Once you are not the SPOK on this project, and there is more exposure to the project we can revisit this issue. Definitely appreciate your proactive approach here in wanting to include it. Just for core base cookbooks that many rely on, we can't add these kind of dependencies.

Thanks for your understanding.

Jennifer

**Comment by melezhik** [comment]
Hi Jennifer! Thanks for feedback. A little remarks : 
> Apologies for the delay in responding. Is sparrow like swat?

[Sparrow](https://github.com/melezhik/sparrow) is a tool to run reusable test suites - also called sparrow plugins , [SparrowHub](https://sparrowhub.org) - is central repository of sparrow plugins  ( like supermarket for chef cookbooks of cpan for perl modules or rubygems for ruby modules - you got the idea ... ). Sparrow plugins are of two types - swat plugins and generic plugins. [outth-mysql-cookbook](https://sparrowhub.org/info/outth-mysql-cookbook) - is generic sparrow plugin to verify some CRUD operations against running mysql server. There is [sparrow cookbook](https://supermarket.chef.io/cookbooks/sparrow) to install sparrow tool chain and optionally sparrow plugins to run them on dedicated hosts. If to say more in abstract way - sparrow is reusable and distributable test suites shipped as packaged software. Like any other software libraries but with focus on testing and monitoring.

So, users could search and install any kind of sparrow plugins, developers could create and upload any kind of new plugins into central repository SparrowHub. The reason I see a good perspective in using sparrow with chef development is as chef heavily relates to software configuration it is logical step to have POST configuration checks which are very wanted  in complex software systems , consider various sparrow plugins for different system parts checks - file system, processes , log file content, crontab entries, web services, software packages, I know chef already has some "embedded"  mechanism for it, but for complex use cases this is probably not enough , or you guys would not stared things like [inspec](https://github.com/chef/inspec) , is it ? :smile: 

Basicly I see your points about other things, the same as you had for httpd cookbook, that's ok. But as I told  there - "chef is a great tool, but I believe that other good tools have to go together to make synergy."

**Pull request closed without merging**
