### PR TITLE
Updated packages for 12.04 and 14.04 too

### PR DESCRIPTION
**Pull request by wilb**
### Description

Updated packages for 12.04 and 14.04 too

### Issues Resolved

[472] [475]

### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by wilb** [comment]
Sorry - just seen you've pushed a release before I got the follow up in.

**Comment by snehitgajjar** [comment]
👍

**Comment by snehitgajjar** [comment]
@tas50 Can you please merge this PR?

**Comment by tas50** [comment]
Thanks for the update

**Pull request merged**
